"""Add vehicle table

Revision ID: a39055845d2f
Revises: 002
Create Date: 2026-01-28 18:23:12.827205
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a39055845d2f'
down_revision: Union[str, None] = '002'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('vehicles',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('license_plate', sa.String(length=20), nullable=False),
    sa.Column('vehicle_type', sa.Enum('Tent', 'Reefer', 'Container', 'Other', name='vehicletype', native_enum=False), nullable=False),
    sa.Column('length', sa.Float(), nullable=False),
    sa.Column('width', sa.Float(), nullable=False),
    sa.Column('height', sa.Float(), nullable=False),
    sa.Column('payload_capacity', sa.Integer(), nullable=False),
    sa.Column('status', sa.Enum('Free', 'In Transit', 'Maintenance', 'Unavailable', name='vehiclestatus', native_enum=False), nullable=False),
    sa.Column('gps_tracker_id', sa.String(length=100), nullable=True),
    sa.Column('current_location', sa.String(length=255), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_vehicles_license_plate'), 'vehicles', ['license_plate'], unique=True)
    op.alter_column('users', 'role',
               existing_type=sa.VARCHAR(length=50),
               type_=sa.Enum('administrator', 'director', 'dispatcher', 'guest', name='userrole', native_enum=False),
               existing_nullable=False,
               existing_server_default=sa.text("'guest'::character varying"))
    op.drop_constraint(op.f('users_email_key'), 'users', type_='unique')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(op.f('users_email_key'), 'users', ['email'], postgresql_nulls_not_distinct=False)
    op.alter_column('users', 'role',
               existing_type=sa.Enum('administrator', 'director', 'dispatcher', 'guest', name='userrole', native_enum=False),
               type_=sa.VARCHAR(length=50),
               existing_nullable=False,
               existing_server_default=sa.text("'guest'::character varying"))
    op.drop_index(op.f('ix_vehicles_license_plate'), table_name='vehicles')
    op.drop_table('vehicles')
    # ### end Alembic commands ###
