"""Add gps_last_updated

Revision ID: 430703469f38
Revises: a39055845d2f
Create Date: 2026-01-28 20:09:21.814564
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '430703469f38'
down_revision: Union[str, None] = 'a39055845d2f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('vehicles', sa.Column('gps_last_updated', sa.DateTime(timezone=True), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('vehicles', 'gps_last_updated')
    # ### end Alembic commands ###
